# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kukirun_msgs/Traffic.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Traffic(genpy.Message):
  _md5sum = "c68a17eb503576fe17e72e4e585ded61"
  _type = "kukirun_msgs/Traffic"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 trafficsign
int32 trafficsign_1
int32 trafficsign_2
int32 trafficsign_3"""
  __slots__ = ['trafficsign','trafficsign_1','trafficsign_2','trafficsign_3']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       trafficsign,trafficsign_1,trafficsign_2,trafficsign_3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Traffic, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.trafficsign is None:
        self.trafficsign = 0
      if self.trafficsign_1 is None:
        self.trafficsign_1 = 0
      if self.trafficsign_2 is None:
        self.trafficsign_2 = 0
      if self.trafficsign_3 is None:
        self.trafficsign_3 = 0
    else:
      self.trafficsign = 0
      self.trafficsign_1 = 0
      self.trafficsign_2 = 0
      self.trafficsign_3 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.trafficsign, _x.trafficsign_1, _x.trafficsign_2, _x.trafficsign_3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.trafficsign, _x.trafficsign_1, _x.trafficsign_2, _x.trafficsign_3,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.trafficsign, _x.trafficsign_1, _x.trafficsign_2, _x.trafficsign_3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.trafficsign, _x.trafficsign_1, _x.trafficsign_2, _x.trafficsign_3,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
