// Generated by gencpp from file kukirun_msgs/Coefficient.msg
// DO NOT EDIT!


#ifndef KUKIRUN_MSGS_MESSAGE_COEFFICIENT_H
#define KUKIRUN_MSGS_MESSAGE_COEFFICIENT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kukirun_msgs
{
template <class ContainerAllocator>
struct Coefficient_
{
  typedef Coefficient_<ContainerAllocator> Type;

  Coefficient_()
    : a0(0.0)
    , a1(0.0)
    , a2(0.0)
    , a3(0.0)  {
    }
  Coefficient_(const ContainerAllocator& _alloc)
    : a0(0.0)
    , a1(0.0)
    , a2(0.0)
    , a3(0.0)  {
  (void)_alloc;
    }



   typedef float _a0_type;
  _a0_type a0;

   typedef float _a1_type;
  _a1_type a1;

   typedef float _a2_type;
  _a2_type a2;

   typedef float _a3_type;
  _a3_type a3;





  typedef boost::shared_ptr< ::kukirun_msgs::Coefficient_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kukirun_msgs::Coefficient_<ContainerAllocator> const> ConstPtr;

}; // struct Coefficient_

typedef ::kukirun_msgs::Coefficient_<std::allocator<void> > Coefficient;

typedef boost::shared_ptr< ::kukirun_msgs::Coefficient > CoefficientPtr;
typedef boost::shared_ptr< ::kukirun_msgs::Coefficient const> CoefficientConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kukirun_msgs::Coefficient_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kukirun_msgs::Coefficient_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kukirun_msgs::Coefficient_<ContainerAllocator1> & lhs, const ::kukirun_msgs::Coefficient_<ContainerAllocator2> & rhs)
{
  return lhs.a0 == rhs.a0 &&
    lhs.a1 == rhs.a1 &&
    lhs.a2 == rhs.a2 &&
    lhs.a3 == rhs.a3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kukirun_msgs::Coefficient_<ContainerAllocator1> & lhs, const ::kukirun_msgs::Coefficient_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kukirun_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kukirun_msgs::Coefficient_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kukirun_msgs::Coefficient_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kukirun_msgs::Coefficient_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kukirun_msgs::Coefficient_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kukirun_msgs::Coefficient_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kukirun_msgs::Coefficient_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kukirun_msgs::Coefficient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02922718d211cab15568610aec8c412d";
  }

  static const char* value(const ::kukirun_msgs::Coefficient_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02922718d211cab1ULL;
  static const uint64_t static_value2 = 0x5568610aec8c412dULL;
};

template<class ContainerAllocator>
struct DataType< ::kukirun_msgs::Coefficient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kukirun_msgs/Coefficient";
  }

  static const char* value(const ::kukirun_msgs::Coefficient_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kukirun_msgs::Coefficient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a0\n"
"float32 a1\n"
"float32 a2\n"
"float32 a3\n"
;
  }

  static const char* value(const ::kukirun_msgs::Coefficient_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kukirun_msgs::Coefficient_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a0);
      stream.next(m.a1);
      stream.next(m.a2);
      stream.next(m.a3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Coefficient_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kukirun_msgs::Coefficient_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kukirun_msgs::Coefficient_<ContainerAllocator>& v)
  {
    s << indent << "a0: ";
    Printer<float>::stream(s, indent + "  ", v.a0);
    s << indent << "a1: ";
    Printer<float>::stream(s, indent + "  ", v.a1);
    s << indent << "a2: ";
    Printer<float>::stream(s, indent + "  ", v.a2);
    s << indent << "a3: ";
    Printer<float>::stream(s, indent + "  ", v.a3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKIRUN_MSGS_MESSAGE_COEFFICIENT_H
