// Generated by gencpp from file kukirun_msgs/Obstacles.msg
// DO NOT EDIT!


#ifndef KUKIRUN_MSGS_MESSAGE_OBSTACLES_H
#define KUKIRUN_MSGS_MESSAGE_OBSTACLES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kukirun_msgs/Obstacle.h>

namespace kukirun_msgs
{
template <class ContainerAllocator>
struct Obstacles_
{
  typedef Obstacles_<ContainerAllocator> Type;

  Obstacles_()
    : obstacles()  {
    }
  Obstacles_(const ContainerAllocator& _alloc)
    : obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::kukirun_msgs::Obstacle_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::kukirun_msgs::Obstacle_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::kukirun_msgs::Obstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kukirun_msgs::Obstacles_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacles_

typedef ::kukirun_msgs::Obstacles_<std::allocator<void> > Obstacles;

typedef boost::shared_ptr< ::kukirun_msgs::Obstacles > ObstaclesPtr;
typedef boost::shared_ptr< ::kukirun_msgs::Obstacles const> ObstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kukirun_msgs::Obstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kukirun_msgs::Obstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kukirun_msgs::Obstacles_<ContainerAllocator1> & lhs, const ::kukirun_msgs::Obstacles_<ContainerAllocator2> & rhs)
{
  return lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kukirun_msgs::Obstacles_<ContainerAllocator1> & lhs, const ::kukirun_msgs::Obstacles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kukirun_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kukirun_msgs::Obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kukirun_msgs::Obstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kukirun_msgs::Obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kukirun_msgs::Obstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kukirun_msgs::Obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kukirun_msgs::Obstacles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kukirun_msgs::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04e65738e06f419f276514823cafe660";
  }

  static const char* value(const ::kukirun_msgs::Obstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04e65738e06f419fULL;
  static const uint64_t static_value2 = 0x276514823cafe660ULL;
};

template<class ContainerAllocator>
struct DataType< ::kukirun_msgs::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kukirun_msgs/Obstacles";
  }

  static const char* value(const ::kukirun_msgs::Obstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kukirun_msgs::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kukirun_msgs/Obstacle[] obstacles\n"
"================================================================================\n"
"MSG: kukirun_msgs/Obstacle\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 radius\n"
"float32 velocity\n"
;
  }

  static const char* value(const ::kukirun_msgs::Obstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kukirun_msgs::Obstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kukirun_msgs::Obstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kukirun_msgs::Obstacles_<ContainerAllocator>& v)
  {
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::kukirun_msgs::Obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKIRUN_MSGS_MESSAGE_OBSTACLES_H
