// Generated by gencpp from file kukirun_msgs/VehiclePose.msg
// DO NOT EDIT!


#ifndef KUKIRUN_MSGS_MESSAGE_VEHICLEPOSE_H
#define KUKIRUN_MSGS_MESSAGE_VEHICLEPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kukirun_msgs
{
template <class ContainerAllocator>
struct VehiclePose_
{
  typedef VehiclePose_<ContainerAllocator> Type;

  VehiclePose_()
    : x(0.0)
    , y(0.0)
    , velocity(0.0)
    , yaw(0.0)  {
    }
  VehiclePose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , velocity(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::kukirun_msgs::VehiclePose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kukirun_msgs::VehiclePose_<ContainerAllocator> const> ConstPtr;

}; // struct VehiclePose_

typedef ::kukirun_msgs::VehiclePose_<std::allocator<void> > VehiclePose;

typedef boost::shared_ptr< ::kukirun_msgs::VehiclePose > VehiclePosePtr;
typedef boost::shared_ptr< ::kukirun_msgs::VehiclePose const> VehiclePoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kukirun_msgs::VehiclePose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kukirun_msgs::VehiclePose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kukirun_msgs::VehiclePose_<ContainerAllocator1> & lhs, const ::kukirun_msgs::VehiclePose_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.velocity == rhs.velocity &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kukirun_msgs::VehiclePose_<ContainerAllocator1> & lhs, const ::kukirun_msgs::VehiclePose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kukirun_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kukirun_msgs::VehiclePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kukirun_msgs::VehiclePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kukirun_msgs::VehiclePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kukirun_msgs::VehiclePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kukirun_msgs::VehiclePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kukirun_msgs::VehiclePose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kukirun_msgs::VehiclePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65d587d5369b55469396df1e25152717";
  }

  static const char* value(const ::kukirun_msgs::VehiclePose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65d587d5369b5546ULL;
  static const uint64_t static_value2 = 0x9396df1e25152717ULL;
};

template<class ContainerAllocator>
struct DataType< ::kukirun_msgs::VehiclePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kukirun_msgs/VehiclePose";
  }

  static const char* value(const ::kukirun_msgs::VehiclePose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kukirun_msgs::VehiclePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 velocity  # [m/s]\n"
"float32 yaw # [radian]\n"
;
  }

  static const char* value(const ::kukirun_msgs::VehiclePose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kukirun_msgs::VehiclePose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.velocity);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehiclePose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kukirun_msgs::VehiclePose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kukirun_msgs::VehiclePose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKIRUN_MSGS_MESSAGE_VEHICLEPOSE_H
